# Generated by Django 3.2.9 on 2024-07-24 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique sensor data identifier', primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(help_text='vehicle unique reference', max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type', models.CharField(help_text='sensor type', max_length=6)),
                ('sensor_value', models.CharField(help_text='sensor value', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
